[workspace]
resolver = "2"

members = [
    "bindings/python",
    "bindings/wasm",
    "dicom-anonymization",
    "dicom-anonymizer-spin",
]

default-members = [
    "bindings/python",
    "bindings/wasm",
    "dicom-anonymization",
]

[profile.release]
lto = true
