name: CI # Continuous Integration

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --release
      - run: git lfs pull
      - name: test
        run: cargo test
      - name: cache
        uses: Swatinem/rust-cache@v2
